### ISSUE TITLE
Bad packaging?

### ISSUE THREAD

**Issue by jim-bo** [cthoyt/onto2nx#5]
Hello, I've installed this code from pip and pip+https to github and no modules appear to be exposed in the current build.
![image](https://user-images.githubusercontent.com/317043/38752779-64e45fd6-3f2a-11e8-9136-210214588c53.png)

**Comment by cthoyt** [comment]
Haha that’s a really good point! I think you’ll have to dig a bit to get to the functions you want. I’m afk for the the weekend, but will make an update when I’m back :)

**Comment by DocThreeC** [comment]
I think that it is still not updated...

**Comment by cthoyt** [comment]
I added some more explicit imports to the top-level init. For me, I got

```bash
(onto2nx) [505] [23:06] [cthoyt@microvac:~/dev/onto2nx]
$ python
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import onto2nx
>>> dir(onto2nx)
['OWLParser', '__author__', '__builtins__', '__cached__', '__copyright__', '__description__', '__doc__', '__email__', '__file__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__title__', '__url__', '__version__', 'aba', 'aba_onto2nx', 'api', 'ontospy', 'owl_rdf', 'owl_xml', 'parse_owl', 'parse_owl_rdf', 'parse_owl_xml', 'utils']
```
