### ISSUE TITLE
loading the ontology to python

### ISSUE THREAD

**Issue by Laya1363** [cthoyt/onto2nx#8]
Hi cthoyt

I have just downloaded onto2nx library and i want to load my ontology which is in .owl format into python and the make list of edges and so on.
searching in the internet I couldn't find any tutorial to learn how I can use onto2nx to convert my ontology to Networkx graph and start to processing. could you please give me some hints?

Thanks in advance

**Comment by PawandeepKaur** [comment]
hello @Laya1363 

I also want to perform the same operation. Did you find out the solution for this?

Thanks

**Comment by rjalexa** [comment]
A few sample lines demostrating how to use onto2nx would be very welcome. would need them too ....

**Comment by cthoyt** [comment]
Hi all, there are better alternatives to this project, so I will archive it. Please see the following alternatives:


-    https://github.com/related-sciences/nxontology (Custom parsing of OWL into NetworkX graphs)
 -   https://github.com/dhimmel/obonet/ (Custom parsing of OBO into NetworkX graphs)
  -  https://github.com/althonos/pronto (General parsing of OBO + OWL)
